package CORBAInterface;


/**
* CORBAInterface/DAMSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Wednesday, 23 February, 2022 4:05:38 PM EST
*/

public interface DAMSInterface extends DAMSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DAMSInterface
