package CORBAInterface;


/**
* CORBAInterface/DAMSInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Wednesday, 23 February, 2022 4:05:38 PM EST
*/

abstract public class DAMSInterfaceHelper
{
  private static String  _id = "IDL:CORBAInterface/DAMSInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, CORBAInterface.DAMSInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CORBAInterface.DAMSInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CORBAInterface.DAMSInterfaceHelper.id (), "DAMSInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CORBAInterface.DAMSInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DAMSInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CORBAInterface.DAMSInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CORBAInterface.DAMSInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBAInterface.DAMSInterface)
      return (CORBAInterface.DAMSInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CORBAInterface._DAMSInterfaceStub stub = new CORBAInterface._DAMSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CORBAInterface.DAMSInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CORBAInterface.DAMSInterface)
      return (CORBAInterface.DAMSInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CORBAInterface._DAMSInterfaceStub stub = new CORBAInterface._DAMSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
