package CORBAInterface;


/**
* CORBAInterface/DAMSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Wednesday, 23 February, 2022 4:05:38 PM EST
*/

public interface DAMSInterfaceOperations 
{

  //administrator Role
  String addAppointment (String AppointmentID, String AppointmentType, int capacity);
  String removeAppointment (String AppointmentID, String AppointmentType);
  String listAppointmentAvailability (String AppointmentType);

  //Patient Role
  String bookAppointment (String patientID, String AppointmentID, String AppointmentType);
  String getAppointmentSchedule (String patientID);
  String cancelAppointment (String patientID, String AppointmentID);
  String swapAppointment (String patientID, String oldAppointmentID, String oldAppointmentType, String newAppointmentID, String newAppointmentType);
  void shutdown ();
} // interface DAMSInterfaceOperations
