package CORBAInterface;

/**
* CORBAInterface/DAMSInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Wednesday, 23 February, 2022 4:05:38 PM EST
*/

public abstract class DAMSInterfaceHolder implements org.omg.CORBA.portable.Streamable, DAMSInterface {
  public CORBAInterface.DAMSInterface value = null;

  public DAMSInterfaceHolder ()
  {
  }

  public DAMSInterfaceHolder (CORBAInterface.DAMSInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBAInterface.DAMSInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBAInterface.DAMSInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBAInterface.DAMSInterfaceHelper.type ();
  }

}
