package CORBAInterface;


/**
* CORBAInterface/DAMSInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface.idl
* Wednesday, 23 February, 2022 4:05:38 PM EST
*/

public abstract class DAMSInterfacePOA extends org.omg.PortableServer.Servant
 implements CORBAInterface.DAMSInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAppointment", new java.lang.Integer (0));
    _methods.put ("removeAppointment", new java.lang.Integer (1));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (2));
    _methods.put ("bookAppointment", new java.lang.Integer (3));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (4));
    _methods.put ("cancelAppointment", new java.lang.Integer (5));
    _methods.put ("swapAppointment", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //administrator Role
       case 0:  // CORBAInterface/DAMSInterface/addAppointment
       {
         String AppointmentID = in.read_string ();
         String AppointmentType = in.read_string ();
         int capacity = in.read_long ();
         String $result = null;
         $result = this.addAppointment (AppointmentID, AppointmentType, capacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CORBAInterface/DAMSInterface/removeAppointment
       {
         String AppointmentID = in.read_string ();
         String AppointmentType = in.read_string ();
         String $result = null;
         $result = this.removeAppointment (AppointmentID, AppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CORBAInterface/DAMSInterface/listAppointmentAvailability
       {
         String AppointmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (AppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //Patient Role
       case 3:  // CORBAInterface/DAMSInterface/bookAppointment
       {
         String patientID = in.read_string ();
         String AppointmentID = in.read_string ();
         String AppointmentType = in.read_string ();
         String $result = null;
         $result = this.bookAppointment (patientID, AppointmentID, AppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CORBAInterface/DAMSInterface/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // CORBAInterface/DAMSInterface/cancelAppointment
       {
         String patientID = in.read_string ();
         String AppointmentID = in.read_string ();
         String $result = null;
         $result = this.cancelAppointment (patientID, AppointmentID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // CORBAInterface/DAMSInterface/swapAppointment
       {
         String patientID = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         String $result = null;
         $result = this.swapAppointment (patientID, oldAppointmentID, oldAppointmentType, newAppointmentID, newAppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // CORBAInterface/DAMSInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CORBAInterface/DAMSInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DAMSInterface _this() 
  {
    return DAMSInterfaceHelper.narrow(
    super._this_object());
  }

  public DAMSInterface _this(org.omg.CORBA.ORB orb) 
  {
    return DAMSInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class DAMSInterfacePOA
